---
title: "Metabolic rate analysis"
author: "Ninah Munk"
date: "2024-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(janitor)
library(emmeans)
library(lme4)
library(Matrix)
library(readxl)
library(tidyr)
library(lmerTest)
library(nlme)
library(car)
library(ggpubr)
library(rstatix)
library(Rmisc)
```


Load Data
```{r}

read.csv("/Users/ninahmunk/Desktop/Projects/Acropora_Regeneration-main/Respiration/Output/full.data.cleaned.csv")-> data
read.csv("/Users/ninahmunk/Desktop/Projects/Acropora_Regeneration-main/Wound_Closure/Data/worm_damage.csv")-> worm
```

Clean up some data and combine data frames
```{r}
data <- rename(data, replace = c("coral_num" = "coral_id"))
data%>%select(-X) -> data

worm%>%select(coral_id, affected, percent_affected)-> worm.damage

data%>%left_join(worm.damage, by = "coral_id")-> data2

```

Run Model
```{r}
#full model
mod2<- lmer(umol.cm2.hr ~ wound*temp*timepoint*percent_affected + (1|genotype/coral_id), data = data2%>%filter(rate == "Respiration"))
anova(mod2)

#reduced model
mod3<- lmer(umol.cm2.hr ~ wound*temp*timepoint + temp*timepoint*percent_affected + (1|genotype/coral_id), data = data2)
anova(mod4)

mod4<- lmer(umol.cm2.hr ~ wound*temp*timepoint + temp*percent_affected + (1|genotype/coral_id), data = data2)
anova(mod4)

```

```{r}
ggplot(data = data2%>%filter(rate == "Respiration", timepoint == "day10"), aes(x = percent_affected, y = umol.cm2.hr))+geom_point()+geom_smooth(method = "lm")+facet_wrap(~temp)

ggplot(data = data2%>%filter(rate == "Respiration", timepoint == "day19"), aes(x = percent_affected, y = umol.cm2.hr))+geom_point()+geom_smooth(method = "lm")+facet_wrap(~wound)

ggplot(data = data2%>%filter(rate == "Gross Photosynthesis", timepoint == "day19"), aes(x = percent_affected, y = umol.cm2.hr))+geom_point()+geom_smooth(method = "lm")+facet_wrap(~temp)

ggplot(data = data2%>%filter(rate == "Gross Photosynthesis", timepoint == "day19"), aes(x = percent_affected, y = umol.cm2.hr))+geom_point()+geom_smooth(method = "lm")+facet_wrap(~wound)


```


```{r}
data3 = subset(data2, percent_affected == 0)
ggplot(data = data3%>%filter(rate == "Respiration", timepoint == "day1"), aes(x = as.factor(temp), y = umol.cm2.hr))+geom_boxplot()
#full model

mod2<- lmer(umol.cm2.hr ~ wound*temp*timepoint + (1|genotype/coral_id), data = data3%>%filter(rate == "Respiration"))
anova(mod2)

#reduced model

mod2a<- lmer(umol.cm2.hr ~ wound*temp + timepoint + (1|genotype/coral_id), data = data3%>%filter(rate == "Respiration"))
anova(mod2a)

mod3<- lmer(umol.cm2.hr ~ wound*temp*timepoint + temp*wound*percent_affected + (1|genotype/coral_id), data = data3%>%filter(rate == "Respiration"))
anova(mod3)

mod4<- lmer(umol.cm2.hr ~ wound*temp*timepoint + temp*percent_affected + (1|genotype/coral_id), data = data3)
anova(mod4)

ggplot(data = data3%>%filter(rate == "Respiration", timepoint == "day1"), aes(x = as.factor(wound), y = umol.cm2.hr))+geom_boxplot()+facet_wrap(~temp)
```

